config/routes.rb
Rails.application.routes.draw do
  resources :decimals
  root to: 'welcomes#index'
  get 'balanceds' => 'balanceds#check'
  post 'balanceds' => 'balanceds#check'
end

app/models/decimal.rb
class Decimal < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/balanceds_controller.rb
class BalancedsController < ApplicationController
	def valid_string?(string)
	  open_paren = ['[','{','(']
	  close_paren = [']','}',')']
	  open_close_hash = {"]"=>"[", "}"=>"{", ")"=>"("}
	  stack = []
	  regex = Regexp.union(close_paren+open_paren)
	  string.scan(regex).each do |char|
	    if open_paren.include? char
	      stack.push(char)
	    elsif close_paren.include? char
	      pop_val = stack.pop
	      return false if pop_val != open_close_hash[char]
	    end
	  end
	  open_paren.none? { |paren| stack.include? paren }
	end

	def check
		@balanceds = params[:text]
    if @balanceds.present?
    	@balan = valid_string?(@balanceds)
      flash[:error] = "#{@balan}"
    end
	end 
end

app/controllers/decimals_controller.rb
class DecimalsController < ApplicationController
  before_action :set_decimal, only: [:show, :edit, :update, :destroy]

  # GET /decimals
  # GET /decimals.json
  def index
    @decimals = Decimal.all
  end

  # GET /decimals/1
  # GET /decimals/1.json
  def show
  end

  # GET /decimals/new
  def new
    @decimal = Decimal.new
  end

  # GET /decimals/1/edit
  def edit
  end

  # POST /decimals
  # POST /decimals.json
  def create
    @decimal = Decimal.new(decimal_params)

    @decimal.ip = NetAddr.i_to_ip(@decimal.number)

    respond_to do |format|
      if @decimal.save
        format.html { redirect_to @decimal, notice: 'Decimal was successfully created.' }
        format.json { render :show, status: :created, location: @decimal }
      else
        format.html { render :new }
        format.json { render json: @decimal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /decimals/1
  # PATCH/PUT /decimals/1.json
  def update
    @decimal = Decimal.find(params[:id])
    @decimal.ip = NetAddr.i_to_ip(@decimal.number)
    respond_to do |format|
      if @decimal.update(decimal_params)
        format.html { redirect_to @decimal, notice: 'Decimal was successfully updated.' }
        format.json { render :show, status: :ok, location: @decimal }
      else
        format.html { render :edit }
        format.json { render json: @decimal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /decimals/1
  # DELETE /decimals/1.json
  def destroy
    @decimal.destroy
    respond_to do |format|
      format.html { redirect_to decimals_url, notice: 'Decimal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_decimal
      @decimal = Decimal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def decimal_params
      params.require(:decimal).permit(:number, :ip)
    end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/balanceds_helper.rb
module BalancedsHelper
end

app/helpers/decimals_helper.rb
module DecimalsHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/balanceds/check.html.erb
<% if !flash[:error].blank? %>
  <div class="alert alert-info" style="width:200px;">
  <%= flash[:error] %>
  </div>
<% end %>
<br />


<%= form_tag({:action => 'check'}, {:id => 'balanceds'}) %>
 <div class="field">
    <%= label_tag :text %><br>
    <%= text_field_tag :text, "",class: 'form-control', style: 'width:200px;', required: true %><div class="show_check"></div>
  </div>
  <div class="actions">
    <%= submit_tag "Check", class: 'btn btn-primary' %>
  </div>

app/views/decimals/_form.html.erb
<%= form_for(@decimal) do |f| %>
  <% if @decimal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@decimal.errors.count, "error") %> prohibited this decimal from being saved:</h2>

      <ul>
      <% @decimal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br>
    <%= f.text_field :number, class: 'form-control', style: 'width:200px;', required: true %>
  </div>
  <div class="actions">
    <%= f.submit "Show IP", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/decimals/edit.html.erb
<h1>Editing</h1>

<%= render 'form' %>

<%= link_to 'Show', @decimal, class: 'btn btn-link' %> |
<%= link_to 'Back', decimals_path, class: 'btn btn-link' %>

app/views/decimals/index.html.erb
<% if !flash[:notice].blank? %>
  <div class="alert alert-info">
  <%= flash[:notice] %>
  </div>
<% end %>
<br />

<h1>Decimals to IP</h1>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Number</th>
      <th>IP</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @decimals.each do |decimal| %>
      <tr>
        <td><%= decimal.number %></td>
        <td><%= decimal.ip %></td>
        <td><%= link_to 'Show', decimal, class: 'btn btn-default btn-sm' %></td>
        <td><%= link_to 'Edit', edit_decimal_path(decimal), class: 'btn btn-success btn-sm' %></td>
        <td><%= link_to 'Destroy', decimal, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Decimal', new_decimal_path, class: 'btn btn-link' %>

app/views/decimals/new.html.erb
<h1>New Decimal</h1>

<%= render 'form' %>

<%= link_to 'Back', decimals_path, class: 'btn btn-link' %>

app/views/decimals/show.html.erb
<% if !flash[:notice].blank? %>
  <div class="alert alert-info">
  <%= flash[:notice] %>
  </div>
<% end %>
<br />

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Number</th>
      <th>IP</th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @decimal.number %></td>
        <td><%= @decimal.ip %></td>
      </tr>
  </tbody>
</table>

<%= link_to 'Edit', edit_decimal_path(@decimal), class: 'btn btn-link' %> |
<%= link_to 'Back', decimals_path, class: 'btn btn-link' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Testonline</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="content">	
	<section>
    <%= yield %>
  </section>
</div>
</body>
</html>

app/views/welcomes/index.html.erb
<%= link_to 'Decimals to IPAddress', new_decimal_path, class: 'btn btn-link' %> |
<%= link_to 'Check balanceds', balanceds_path, class: 'btn btn-link' %>